CREATE DATABASE Диплом
GO

USE [Диплом]
GO

/****** Object:  Table [dbo].[Connection]    Script Date: 07.05.2025 0:12:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Connection](
	[OrderID] [int] NOT NULL,
	[EmployeeID] [int] NOT NULL,
	[OrderStatus] [bit] NOT NULL
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Employee]    Script Date: 07.05.2025 0:12:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Employee](
	[EmployeeID] [int] NOT NULL,
	[FullName] [nvarchar](70) NOT NULL,
	[NumberPhone] [nvarchar](15) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
	[Adress] [nvarchar](500) NOT NULL,
	[PassportSeries] [nvarchar](10) NOT NULL,
	[PassportNumber] [nvarchar](10) NOT NULL,
	[PassportGivenBy] [nvarchar](300) NOT NULL,
	[PassportGivenDateGivenBy] [nvarchar](10) NOT NULL,
	[Registration] [nvarchar](500) NOT NULL,
	[INN] [nvarchar](20) NOT NULL,
	[SNILS] [nvarchar](20) NOT NULL,
	[Post] [nvarchar](50) NULL,
 
 CONSTRAINT [EmployeeID] PRIMARY KEY CLUSTERED 
([EmployeeID] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 
 CONSTRAINT [Email] UNIQUE NONCLUSTERED 
([Email] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 
 CONSTRAINT [INN] UNIQUE NONCLUSTERED 
([INN] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 
 CONSTRAINT [NumberPhone] UNIQUE NONCLUSTERED 
([NumberPhone] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 
 CONSTRAINT [PassportNumber, PassportSeries] UNIQUE NONCLUSTERED 
([PassportNumber] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],

 CONSTRAINT [SNILS] UNIQUE NONCLUSTERED 
([SNILS] ASC)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
)

ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Order]    Script Date: 07.05.2025 0:12:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Order](
	[OrderID] [int] NOT NULL,
	[OrderName] [nvarchar](150) NOT NULL,
	[OrderDescription] [nvarchar](3000) NOT NULL,
 CONSTRAINT [PK_Table_2] PRIMARY KEY CLUSTERED 
(
	[OrderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Connection]  WITH CHECK ADD  CONSTRAINT [Connection_Table_1] FOREIGN KEY([EmployeeID])
REFERENCES [dbo].[Employee] ([EmployeeID])
GO

ALTER TABLE [dbo].[Connection] CHECK CONSTRAINT [Connection_Table_1]
GO

ALTER TABLE [dbo].[Connection]  WITH CHECK ADD  CONSTRAINT [Connection_Table_2] FOREIGN KEY([OrderID])
REFERENCES [dbo].[Order] ([OrderID])
GO

ALTER TABLE [dbo].[Connection] CHECK CONSTRAINT [Connection_Table_2]
GO

